name: dotnet-test

on:
    push:
        paths-ignore:
          - '*.md'  # Exclure les fichiers .md
          - '**/*.yml' # Exclure les fichiers .yml
          
    
jobs:
  build_and_test:

    runs-on: windows-2022

    steps:
    
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - name: Setup .NET 6
      uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
      with:
          dotnet-version: 6.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug
      
    - name: Test
      run: dotnet test --configuration Debug
